### ISSUE TITLE
To ensure adoption of quadwild, provide binaries for Windows, Mac and Linux.

### ISSUE THREAD

**Issue by fire** [nicopietroni/quadwild#1]
# To ensure adoption of quadwild, provide binaries for Windows, Mac and Linux.

- Status: proposed 
- Deciders: V-Sekai,fire,
- Tags: V-Sekai,quadwild

## Context and Problem Statement

quadwild appears to only be a source distribution on github.

I want to make the technology more accessible.

## Describe the proposed option and how it helps to overcome the problem or limitation

Use github actions to automatically build quadwild for Windows, Mac, and Linux.

## Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams

1. Switch from gurobi to anything that can be redistributed and remixed.
1. Automate Linux builds
2. flatpak? appimage?
3. Automate Windows builds
4. Automate Macos builds
5. Default to organic shapes for my characters usecase.
5. Package all three platforms into the releases section.

## Positive Consequences 

- Widespread adoption
- Allows making an external addon for Blender

## Negative Consequences 

- Requires devops work.

## Option graveyard: 

- Option: Keep the current situation.
- Rejection Reason: It is difficult to build.

## If this enhancement will not be used often, can it be worked around with a few lines of script?

This not a small github action.

## Is there a reason why this should be core and done by us?

Wanted to share the work with the quadwild maintainers.

## References 

- https://github.com/nicopietroni/quadwild/

**Comment by nicopietroni** [comment]
dear Fire,
I know we should provide also precompiled binaries. 
Unfortunately, Gurobi is not open source, but there are free licenses for academia.
We are planning to switch to something open-source, however, so far, nothing has comparable performances
Maybe we can have a look after Siggraph Deadline and see if we can switch to something we can distribute

**Comment by gabriel-lucas** [comment]
First of all congratulations for your impressive work.
I think the proposal made by @fire would be very valuable.

I arrived at quadwild because I was looking for a remeshing addon for Blender and it was mentioned here: 
https://github.com/jayanam/jremesh-tools/issues/2

The addon released by @jayanam could be integrating quadwild 
https://www.blendermarket.com/products/jremesh-tools
https://github.com/jayanam/jremesh-tools
https://www.youtube.com/watch?v=_HqngZdY1Ww

I searched for libraries that support MIQP (Mixed-integer quadratic programming), maybe they could replace gurobi.

PYOMO - https://github.com/Pyomo/pyomo
CASIDI - https://github.com/casadi/casadi
CVXPY - https://www.cvxpy.org/examples/basic/mixed_integer_quadratic_program.html
MIOSCQP - https://github.com/osqp/miosqp
PYMIQP - https://github.com/sschnug/pyMIQP
SONNET - https://github.com/coin-or/Sonnet/issues/3#issuecomment-756244970

Thanks

**Comment by vensauro** [comment]
https://github.com/cgg-bern/quadwild-bimdf
here have a solution without gurobi

**Comment by fire** [comment]
I have tested [quadwild-bimdf](https://github.com/cgg-bern/quadwild-bimdf) and it works.

**Comment by jesuiskiki** [comment]
> I have tested [quadwild-bimdf](https://github.com/cgg-bern/quadwild-bimdf) and it works.

I wonder if you could help me with the command lines when dealing with an .obj file using quadwild-bimdf-0.0.1-windows.zip ?
https://github.com/cgg-bern/quadwild-bimdf/issues/14
